// Generated by gencpp from file virtual_blinker/CarState.msg
// DO NOT EDIT!


#ifndef VIRTUAL_BLINKER_MESSAGE_CARSTATE_H
#define VIRTUAL_BLINKER_MESSAGE_CARSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace virtual_blinker
{
template <class ContainerAllocator>
struct CarState_
{
  typedef CarState_<ContainerAllocator> Type;

  CarState_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , speed(0.0)
    , id(0)
    , t(0)  {
    }
  CarState_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , speed(0.0)
    , id(0)
    , t(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef float _speed_type;
  _speed_type speed;

   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _t_type;
  _t_type t;





  typedef boost::shared_ptr< ::virtual_blinker::CarState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::virtual_blinker::CarState_<ContainerAllocator> const> ConstPtr;

}; // struct CarState_

typedef ::virtual_blinker::CarState_<std::allocator<void> > CarState;

typedef boost::shared_ptr< ::virtual_blinker::CarState > CarStatePtr;
typedef boost::shared_ptr< ::virtual_blinker::CarState const> CarStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::virtual_blinker::CarState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::virtual_blinker::CarState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace virtual_blinker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'virtual_blinker': ['/home/lu/catkin_ws/src/virtual_blinker/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::virtual_blinker::CarState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::virtual_blinker::CarState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::virtual_blinker::CarState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::virtual_blinker::CarState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::virtual_blinker::CarState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::virtual_blinker::CarState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::virtual_blinker::CarState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9038b65c4bd5219fecca0d10618172a1";
  }

  static const char* value(const ::virtual_blinker::CarState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9038b65c4bd5219fULL;
  static const uint64_t static_value2 = 0xecca0d10618172a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::virtual_blinker::CarState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "virtual_blinker/CarState";
  }

  static const char* value(const ::virtual_blinker::CarState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::virtual_blinker::CarState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 theta\n\
float32 speed\n\
int32 id\n\
int32 t\n\
";
  }

  static const char* value(const ::virtual_blinker::CarState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::virtual_blinker::CarState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.speed);
      stream.next(m.id);
      stream.next(m.t);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::virtual_blinker::CarState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::virtual_blinker::CarState_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "t: ";
    Printer<int32_t>::stream(s, indent + "  ", v.t);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIRTUAL_BLINKER_MESSAGE_CARSTATE_H
